[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
rental = "5NKJtqgRw4dcLSX7nqNmLAbHKuodRctZ9LzLsHcZnbfZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./tests/wallet.json"
# wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
